[theme]
primaryColor = "#4a90e2"
backgroundColor = "#1a1a2e"
secondaryBackgroundColor = "#16213e"
textColor = "#ffffff"
font = "Space Grotesk"

[server]
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false 